#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/User/OneDrive - UBC/UBC/Courses/Year 4/CPSC 427/MainRepo/Team17/"
